name: MunafaBot Auto Runner

on:
  schedule:
    - cron: '50 3 * * 1-5'  # Daily 9:20 AM IST
    - cron: '0 8 * * 4'     # Thursday 1:30 PM IST
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Bot
      run: python main.py
      env:
        API_KEY: ${{ secrets.API_KEY }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        FEED_TOKEN: ${{ secrets.FEED_TOKEN }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
